### ISSUE TITLE
Selecionar e copiar Code Highlight

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#41]
Olá, gostaria de sugerir uma funcionalidade para o Code Highlight.

Hoje para copiarmos o código da transcrição, é necessário selecionar todo o código manualmente.

Não sei se é possível criar essa funcionalidade, mas seria muito bom poder clicar dentro da Code Highlight e apenas acionar o atalho `ctrl + A` para poder selecionar todo o código, e copiar em seguida. Assim não correria o risco de não copiar alguma linha do código e seria mais prático e rápido. 

**Exemplos de Code Highlight:**

~~~bash
$ ansible-playbook provisioning.yml -u vagrant -i hosts --private-key .vagrant/machines/wordpress/virtualbox/private_key

PLAY [all] ************************************************************************************************************
~~~
```yml
$ ansible-playbook provisioning.yml -u vagrant -i hosts --private-key .vagrant/machines/wordpress/virtualbox/private_key

PLAY [all] ************************************************************************************************************
```

**Comment by designernatan** [comment]
oi @thdesous , em qual parte da alura que voce precisa copiar os codigos hoje?

valeu pela sugestão!

**Comment by thdesous** [comment]
@designernatan nas transcrições. 

Exemplo:

```
tasks:
  - name: 'Instala pacotes de dependencia do sistema operacional'
    apt:
      name: "{{ item }}"
      state: latest
    become: yes
    with_items:
      - php5
      - apache2
      - libapache2-mod-php5
      - php5-gd
      - libssh2-php
      - php5-mcrypt
      - mysql-server-5.6
      - python-mysqldb
      - php5-mysql

  - name: 'Baixa o arquivo de instalação do Wordpress'
    get_url:
      url: 'http://wordpress.org/lastest.tar.gz'
      dest: '/tmp/wordpress.tar.gz'
```
